// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgKNpA0f0zxxZQoYTMIesDKmBXPdtZ9ZE',
    appId: '1:823718437608:web:79fa30616246c2a70b9f5d',
    messagingSenderId: '823718437608',
    projectId: 'fashion-app-7bd03',
    authDomain: 'fashion-app-7bd03.firebaseapp.com',
    storageBucket: 'fashion-app-7bd03.firebasestorage.app',
    measurementId: 'G-57DL7N7P6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyXTRT352ofZUqgFgVnmKTNJ_kKT11ZN8',
    appId: '1:823718437608:android:a5d21d9a326a241b0b9f5d',
    messagingSenderId: '823718437608',
    projectId: 'fashion-app-7bd03',
    storageBucket: 'fashion-app-7bd03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFq7saf475C7wxt7W8q0yr6YY5z0tTecE',
    appId: '1:823718437608:ios:ef73fe8cbc7bb2f30b9f5d',
    messagingSenderId: '823718437608',
    projectId: 'fashion-app-7bd03',
    storageBucket: 'fashion-app-7bd03.firebasestorage.app',
    iosBundleId: 'com.example.fashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFq7saf475C7wxt7W8q0yr6YY5z0tTecE',
    appId: '1:823718437608:ios:ef73fe8cbc7bb2f30b9f5d',
    messagingSenderId: '823718437608',
    projectId: 'fashion-app-7bd03',
    storageBucket: 'fashion-app-7bd03.firebasestorage.app',
    iosBundleId: 'com.example.fashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgKNpA0f0zxxZQoYTMIesDKmBXPdtZ9ZE',
    appId: '1:823718437608:web:1feaceb73bc3cc410b9f5d',
    messagingSenderId: '823718437608',
    projectId: 'fashion-app-7bd03',
    authDomain: 'fashion-app-7bd03.firebaseapp.com',
    storageBucket: 'fashion-app-7bd03.firebasestorage.app',
    measurementId: 'G-19XWW94Q0B',
  );
}
